# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
link_with 'OssAPI'
# Uncomment this line if you're using Swift
use_frameworks!

target 'OssAPI' do
pod 'Alamofire'
pod 'ObjectMapper', '~> 1.3'
pod 'Locksmith'
pod 'SwiftyBeaver'
pod 'ReactKit'
end
